esphome:
  name: smartclock-async-test
  friendly_name: "SmartClock AsyncWebServer Test"

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "SmartClock-Test"
    password: "smartclock123"

logger:
  level: DEBUG

ota:
  - platform: esphome

api:

# BELANGRIJK: web_server_base is nodig voor AsyncWebServer
web_server_base:

# Optioneel: ESPHome's standaard web interface (andere poort of uitschakelen)
# web_server:
#   port: 8080  # Anders dan 80

# Test component met AsyncWebServer
external_components:
  - source:
      type: local
      path: library
    components: [ smartclock_v2 ]

smartclock_v2:
  id: test_component
